//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationSystem.Migrations {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2020 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class _202009071629174_ADdMeteringDevice {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a 202009071629174_ADdMeteringDevice object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public _202009071629174_ADdMeteringDevice() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("CalculationSystem.Migrations.202009071629174_ADdMeteringDevice", typeof(_202009071629174_ADdMeteringDevice).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'dbo'.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString(ResourceNames.DefaultSchema, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'H4sIAAAAAAAEAO1c3W7jNha+L7DvIOhqt5jaSeamDewWqT3TBp0kgzhT7F4NaIl2hNWPV6TSBIt9sl70kfoKeyRRFMUfiZJsJzMdFCgmIs/h4eF3eA6pT/7z9z9mPzxGofOAUxIk8dw9nZy4Do69xA/i7dzN6Oabb90fvv/bV7M3fvTo/Fr1e533A8mYzN17Snfn0ynx7nGEyCQKvDQhyYZOvCSaIj+Znp2cfDc9PZ1iUOGCLseZ3WYxDSJc/AF/LpLYwzuaofAq8XFI2HNoWRVanWsUYbJDHp67CxR6WYgo2LF6IhRHk+XadS7CAIEtKxxuXAfFcUKLHucfCF7RNIm3qx08QOHd0w5Dvw0KCWYzOK+7207m5CyfzLQWrFR5GaFJ1FPh6WvmnaksPsjHLvce+O8N+Jk+5bMufDh3LzwvAee7jjzW+SJM8346DxdaAkwmTPqVo/R5xcEBGMr/gz5ZSLMUz2Oc0RSFr5z32ToMvF/w013ybxzP4ywMRWPB [rest of string was truncated]&quot;;'.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString(ResourceNames.Target, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'DefaultSchema'.
            /// </summary>
            public const string DefaultSchema = "DefaultSchema";
            
            /// <summary>
            /// Stores the resource name 'Target'.
            /// </summary>
            public const string Target = "Target";
        }
    }
}
