// <auto-generated />
namespace CalculationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Houseadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Houseadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202001281715162_House added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
