//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationSystem.Migrations {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2020 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class _202009061939193_AddMeteringDevice {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a 202009061939193_AddMeteringDevice object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public _202009061939193_AddMeteringDevice() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("CalculationSystem.Migrations.202009061939193_AddMeteringDevice", typeof(_202009061939193_AddMeteringDevice).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'dbo'.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString(ResourceNames.DefaultSchema, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'H4sIAAAAAAAEAO1c3W7jNha+X2DfQdBVdzG1k8zNNrBbpPZMG3SSDOJM0V4NaIl2hNWPV6SyCRb7ZL3YR9pX6JFEURR/JEqyncwgGGCQiDyHh+d8hzykPuX/f/xv9sNjFDoPOCVBEs/d08mJ6+DYS/wg3s7djG6+/Yf7w/d//cvsnR89Or9W/d7m/UAyJnP3ntLd+XRKvHscITKJAi9NSLKhEy+JpshPpmcnJ99NT0+nGFS4oMtxZrdZTIMIF7/Ar4sk9vCOZii8SnwcEvYcWlaFVucaRZjskIfn7gKFXhYiCnasngjF0WS5dp2LMEBgywqHG9dBcZzQosf5J4JXNE3i7WoHD1B497TD0G+DQoLZDM7r7raTOTnLJzOtBStVXkZoEvVUePqWeWcqiw/yscu9B/57B36mT/msCx/O3QvPS8D5riOPdb4I07yfzsOFlgCTCZN+4yh93nBwAIbyf9AnC2mW4nmMM5qi8I3zMVuHgfcLfrpL/onjeZyFoWgs [rest of string was truncated]&quot;;'.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString(ResourceNames.Target, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'DefaultSchema'.
            /// </summary>
            public const string DefaultSchema = "DefaultSchema";
            
            /// <summary>
            /// Stores the resource name 'Target'.
            /// </summary>
            public const string Target = "Target";
        }
    }
}
