// <auto-generated />
namespace CalculationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Price_Service_Account_Relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Price_Service_Account_Relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202002112011266_Price_Service_Account_Relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
